#!/usr/bin/env bash

BIN=node_modules/.bin
DST=public

PANELS_VERSION=`.bin/version panels`
PANELS_DST=$DST/panels-$PANELS_VERSION
VENDOR_VERSION=`.bin/version vendor`
VENDOR_DST=$DST/vendor-$VENDOR_VERSION

echo "[bundle] bundling panels..."
mkdir -p $DST

echo "[bundle] processing vendor v${VENDOR_VERSION}..."
$BIN/browserify --verbose --debug \
  --require can-use-dom \
  --require lite-url \
  --require lodash.debounce \
  --require panels-ui \
  --require path-browserify \
  --require raf \
  --require react \
  --require react-dom \
  --require react-redux \
  --require redux \
  --require redux-logger \
  --require redux-promise \
  --require redux-thunk \
  --require rlookup \
  --extension .es6 \
  --transform babelify \
  --transform envify \
  vendor.es6 | \
  $BIN/exorcist $VENDOR_DST.js.map > $VENDOR_DST.js &&
  $BIN/uglifyjs --verbose \
    --compress \
    --mangle \
    --screw-ie8 \
    --in-source-map $VENDOR_DST.js.map \
    --source-map $VENDOR_DST.min.js.map $VENDOR_DST.js > $VENDOR_DST.min.js
echo "[bundle] vendor done"
ls -lha $VENDOR_DST.*

echo "[bundle] processing panels v${PANELS_VERSION}..."
$BIN/browserify --debug --verbose \
  --no-bundle-external \
  --extension .es6 \
  --transform babelify \
  --transform envify \
  index.es6 | \
  $BIN/exorcist $PANELS_DST.js.map > $PANELS_DST.js &&
  $BIN/uglifyjs --verbose \
    --compress \
    --mangle \
    --screw-ie8 \
    --in-source-map $PANELS_DST.js.map \
    --source-map $PANELS_DST.min.js.map $PANELS_DST.js > $PANELS_DST.min.js
echo "[bundle] panels done"
ls -lha $PANELS_DST.*

echo "[bundle] done"
