#!/usr/bin/env bash

BIN=node_modules/.bin
BUNDLE=bundle

VERSION=$1
PANELS=$BUNDLE/panels-$VERSION

echo "[bundle] bundling panels..."
mkdir -p $BUNDLE

echo "[bundle] v${VERSION}..."
NODE_ENV=development $BIN/browserify --verbose --debug \
  --require lodash.debounce \
  --require mini-unique-id \
  --require panels-normalise-uri \
  --require panels-ui \
  --require react \
  --require react-dom \
  --require react-redux \
  --require redux \
  --require redux-logger \
  --require ./utils/redux-promise:redux-promise \
  --require redux-thunk \
  --require style-to-css \
  --require waiting \
  --transform [rollupify --config rollup.config.js] \
  --transform loose-envify \
  index.dev.js > $PANELS.js

ls -lha $PANELS.*
echo "[bundle] done"
