#!/usr/bin/env bash

BIN=node_modules/.bin
BUNDLE=bundle

VERSION=$1
PANELS=$BUNDLE/panels-$VERSION

echo "[bundle-dev] watching panels..."

mkdir -p $BUNDLE
NODE_ENV=development $BIN/watchify --verbose --debug \
  --require lodash.debounce \
  --require mini-unique-id \
  --require panels-normalise-uri \
  --require panels-ui \
  --require react \
  --require react-addons-transition-group \
  --require react-dom \
  --require react-flip-move \
  --require react-redux \
  --require redux \
  --require redux-logger \
  --require ./utils/redux-promise:redux-promise \
  --require redux-thunk \
  --require style-to-css \
  --require waiting \
  --require ./index.dev.js:panels \
  --transform [rollupify --config rollup.config.js] \
  --transform loose-envify \
  --entry index.dev.js \
  --outfile $PANELS.js
