#!/usr/bin/env bash

BIN=node_modules/.bin
BUNDLE=bundle

VERSION=$1
PANELS=$BUNDLE/panels-$VERSION

echo "[bundle] bundling panels..."
mkdir -p $BUNDLE

echo "[bundle] v${VERSION}..."
NODE_ENV=production $BIN/browserify --verbose --debug \
  --exclude react \
  --require ./node_modules/react/cjs/react.production.min.js:react \
  --exclude react-dom \
  --require ./node_modules/react-dom/cjs/react-dom.production.min.js:react-dom \
  --require prop-types \
  --require ./index.js:panels \
  --require ./panels-ui-compat.js:panels-ui \
  --require ./blocks/index.js:panels/blocks \
  --require ./utils/normalise-uri/index.js:panels/normalise-uri \
  --require ./utils/snap.js:panels/snap \
  --transform [ babelify ] \
  --entry index.js | \
  $BIN/exorcist $PANELS-prod.js.map > $PANELS-prod.js &&
  $BIN/uglifyjs $PANELS-prod.js -o $PANELS.min.js -c -m

ls -lha $PANELS.*
echo "[bundle] done"