#!/usr/bin/env bash

BIN=node_modules/.bin
BUNDLE=bundle

VERSION=$1
PANELS=$BUNDLE/panels-$VERSION

echo "[bundle] bundling panels..."
mkdir -p $BUNDLE

echo "[bundle] v${VERSION}..."
NODE_ENV=development $BIN/browserify --verbose --debug \
  --require lodash.debounce \
  --require mini-unique-id \
  --require panels-normalise-uri \
  --require panels-ui \
  --require react \
  --require react-addons-transition-group \
  --require react-dom \
  --require react-flip-move \
  --require react-redux \
  --require redux \
  --require redux-logger \
  --require ./utils/redux-promise:redux-promise \
  --require redux-thunk \
  --require style-to-css \
  --require waiting \
  --require ./index.dev.js:panels \
  --transform [rollupify --config rollup.config.js] \
  --transform loose-envify \
  --entry index.dev.js | \
  $BIN/exorcist $PANELS.js.map > $PANELS.js

NODE_ENV=production $BIN/browserify --verbose --debug \
  --require lodash.debounce \
  --require mini-unique-id \
  --require panels-normalise-uri \
  --require panels-ui \
  --require react \
  --require react-addons-transition-group \
  --require react-dom \
  --require react-flip-move \
  --require react-redux \
  --require redux \
  --require ./utils/redux-promise:redux-promise \
  --require redux-thunk \
  --require style-to-css \
  --require waiting \
  --require ./index.dev.js:panels \
  --transform [rollupify --config rollup.config.js] \
  --transform loose-envify \
  --entry index.dev.js | \
  $BIN/exorcist $PANELS-prod.js.map > $PANELS-prod.js &&
  $BIN/uglifyjs --verbose \
    --compress \
    --mangle \
    --screw-ie8 \
    --in-source-map $PANELS-prod.js.map \
    --source-map $PANELS.min.js.map $PANELS-prod.js > $PANELS.min.js
rm $PANELS-prod*

ls -lha $PANELS.*
echo "[bundle] done"
