#!/usr/bin/env bash

git pull &&
git push &&
npm run clean &&
npm run build &&
rm -rf bundle &&
npm run bundle `node -e "console.log(require('./package.json').version)"` &&
npm publish &&
npm run clean
