#!/usr/bin/env bash

read -p "New version (enter nothing for patch): " VERSION;
VERSION=${VERSION:-patch};

git pull &&
git push &&
npm version $VERSION &&
npm run clean &&
NODE_ENV=production npm run bundle &&
BABEL_ENV=server npm run build &&
npm publish &&
git push --follow-tags &&
npm run clean
