#!/usr/bin/env bash

BIN=node_modules/.bin

function run {
  NODE_ENV=development rollup -i ./playground/$1/src.js -o ./rollup-bundle/$1-app.js -c rollup.config.js
  NODE_ENV=development $BIN/watchify --debug --verbose \
    --plugin esmify \
    --external panels \
    --external panels/blocks \
    --external panels/normalise-uri \
    --external panels/snap \
    --external react \
    --external react-dom \
    --external velocity-react \
    --require ./rollup-bundle/$1-app.js:$1 \
    --outfile ./playground/$1/app.js
}

run trails.panels.localhost &
run launchpad.panels.localhost &
run launchpad-floating.panels.localhost &
run toc.localhost &
run notes.localhost &
NODE_ENV=development rollup -i ./playground/custom-parser.panels.localhost/app/src.js -o ./rollup-bundle/custom-parser.panels.localhost-app.js -c rollup.config.js
NODE_ENV=development $BIN/watchify --debug --verbose \
  --plugin esmify \
  --external panels \
  --external panels/blocks \
  --external panels/normalise-uri \
  --external panels/snap \
  --external react \
  --external react-dom \
  --external velocity-react \
  --require ./rollup-bundle/custom-parser.panels.localhost-app.js:custom-parser.panels.localhost \
  --outfile ./playground/custom-parser.panels.localhost/app/app.js &
NODE_ENV=development rollup -i index.dev.js -o ./rollup-bundle/rollup-index.dev.js -c rollup.config.js
NODE_ENV=development $BIN/watchify --debug --verbose \
  --plugin esmify \
  --require react \
  --require react-dom \
  --require velocity-react \
  --require ./blocks/index.js:panels/blocks \
  --require ./utils/normalise-uri/index.js:panels/normalise-uri \
  --require ./utils/snap.js:panels/snap \
  --outfile ./playground/panels.js ./rollup-bundle/rollup-index.dev.js &
$BIN/babel-node --plugins @babel/plugin-transform-modules-commonjs .bin/server.js &
  wait
